### ISSUE TITLE
Problem with Java version bumped from 8 to 11

### ISSUE THREAD

**Issue by dillense** [jenkins-infra/github-reusable-workflows#13]
Hello,
I was successfully using jenkins-infra/github-reusable-workflows/.github/workflows/maven-cd.yml@v1 for a plugin CD workflow, but it now fails (since [this commit](https://github.com/jenkins-infra/github-reusable-workflows/commit/ae8dc99984a1534313cc45909b5365e37dec1905) I guess).
As a matter of fact, this plug-in builds only with Java 8. How could I handle this?

**Comment by jglick** [comment]
(Since #6.)

> this plug-in builds only with Java 8

Fix that? https://github.com/jenkinsci/clif-performance-testing-plugin/pull/14
