### ISSUE TITLE
CD broken in repo using restricted default permissions for `GITHUB_TOKEN`

### ISSUE THREAD

**Issue by jglick** [jenkins-infra/github-reusable-workflows#23]
https://github.com/jenkinsci/secure-requester-whitelist-plugin/actions/runs/4294658824 for example. https://github.com/jenkinsci/secure-requester-whitelist-plugin/settings/actions shows **Workflow permissions** set to **Read repository contents and packages permissions**, not **Read and write permissions** as in other CD-enabled repos. I think we now need to set `permissions` as per https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token. I am confused since https://github.blog/changelog/2023-02-02-github-actions-updating-the-default-github_token-permissions-to-read-only/ says

> New repositories will inherit permissions from parent organization.

so was this changed in @jenkinsci recently? CC @lemeurherve @timja

**Comment by timja** [comment]
this is what's setup at the org level:
https://github.com/organizations/jenkinsci/settings/actions

![image](https://user-images.githubusercontent.com/21194782/221908229-4492d7da-b47f-4359-b051-d055dd0e54e8.png)

**Comment by lemeurherve** [comment]
I haven't seen anything related to this kind of change either.

FTR, here is the current settings on @jenkins-infra org:

<img width="957" alt="image" src="https://user-images.githubusercontent.com/91831478/221908293-82e052a9-3593-44c5-b3d5-1237d865aba8.png">

**Comment by jglick** [comment]
:shrug: I am checking whether this is something I can correct in the repo’s `.github/workflows/cd.yaml`…

**Comment by lemeurherve** [comment]
I've created a new repo for check on @jenkins-infra, FWIW the setting is correctly inherited:
https://github.com/jenkins-infra/test-repo-check-action-workflow-default-permission/settings/actions

<img width="822" alt="image" src="https://user-images.githubusercontent.com/91831478/221909065-a59aa806-2504-420b-958c-f772dcf67e67.png">

**Comment by jglick** [comment]
Well this was not a new repo, it was an old repo with Actions newly enabled.

**Comment by lemeurherve** [comment]
About the ci.jenkins.io GitHub app, the only recent change I can think of was me adding a @jenkins-infra repository to the 101 @jenkins-infra ones it has access to, cf https://github.com/jenkins-infra/helpdesk/issues/3409#issuecomment-1446929239

<img width="837" alt="image" src="https://user-images.githubusercontent.com/91831478/221911812-9e8bd272-d05e-4f45-820e-b0ac73de0ac3.png">

As far as I know, it has access to all @jenkinsci repositories:

<img width="540" alt="image" src="https://user-images.githubusercontent.com/91831478/221912095-e8417e60-dfc7-4afa-9398-dd24e75633e6.png">

**Comment by timja** [comment]
o interesting you can close cross-org now

**Comment by daniel-beck** [comment]
Re `jenkinsci/secure-requester-whitelist-plugin`, I'm pretty sure this was me [when I played with the corresponding metadata in Jenkins Security Scan](https://github.com/jenkinsci/secure-requester-whitelist-plugin/commit/e67896c90377214d687a01b7151deec28bf63ff2).

**Comment by jglick** [comment]
Ah! Well, it is still a good practice to explicitly declare the expected permissions—means this workflow should run regardless of how a particularly repository is set up.
