### ISSUE TITLE
New release needed to avoid deprecated action

### ISSUE THREAD

**Issue by jonesbusy** [jenkins-infra/github-reusable-workflows#28]
### What feature do you want to see added?

Action are renovated and updated main branch.

But reusable workflow was not released since long time and now cause deprecation issue when CD is running

![node_eol](https://github.com/jenkins-infra/github-reusable-workflows/assets/825750/8b6e75d2-ab7b-4a1a-846b-48bad05c9692)

Node16 is EOL since 5 month ago.

**Comment by lemeurherve** [comment]
https://github.com/jenkins-infra/github-reusable-workflows/releases/tag/v1.1.3

**Comment by jonesbusy** [comment]
Well for me it's not yet fixed. One release of yesterday still triggers warnings : https://github.com/jenkinsci/flyway-api-plugin/actions/runs/7947376727

https://raw.githubusercontent.com/jenkinsci/.github/master/workflow-templates/cd.yaml still point to a release that doesn't contains #29

**Comment by weisun10** [comment]
> https://github.com/jenkins-infra/github-reusable-workflows/releases/tag/v1.1.3

@lemeurherve the v1.1.3 was released on Oct 22, 2022. could you please help to release a new one?
![image](https://github.com/jenkins-infra/github-reusable-workflows/assets/10278772/0e159bef-88f1-4268-a948-dae7a914e0d8)
