### ISSUE TITLE
Make java version an input

### ISSUE THREAD

**Issue by jetersen** [jenkins-infra/github-reusable-workflows#5]
https://github.com/jenkins-infra/github-reusable-workflows/blob/1b4d109fd867c7ae7ae74ce65ffb0c1f0beeb051/.github/workflows/maven-cd.yml#L60

@jglick I think it might be useful to make this a variable or do you think we can transition once and for all? 😆

**Comment by jglick** [comment]
I think we can just switch to 11. Any reasonably recent plugin should build fine on 11. This action runs no tests so there is no concern about accidentally releasing something broken on 8.

**Comment by jetersen** [comment]
Since `11` is [default on github's virtual environments for ubuntu](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md#java) I think that makes sense.
